// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idgsbwbioxdnjazmtedc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkZ3Nid2Jpb3hkbmphem10ZWRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNjA5NDcsImV4cCI6MjA2MjYzNjk0N30.xine9hv3iCLsRBIikcvI21FeYX7VKfRrc1C-bBKGPwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);